package fideflix.interfaz;

import fideflix.red.Protocolo;
import fideflix.red.ServidorFideflix;
import java.io.IOException;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * VENTANA DEL SERVIDOR (version para el DISENADOR de NetBeans).
 *
 * Misma funcionalidad que la version hecha a mano, pero con la estructura
 * que genera el editor de formularios: initComponents() dentro de bloques
 * GEN-BEGIN/GEN-END (regenerados desde VentanaServidor.form) y la logica
 * en los manejadores de eventos.
 *
 * Para usarla: copiar VentanaServidor.java Y VentanaServidor.form JUNTOS
 * a src/fideflix/interfaz (NetBeans los empareja por nombre).
 *
 * La logica es identica: auto-arranque en el constructor, log siempre via
 * SwingUtilities.invokeLater (los mensajes llegan desde hilos de red y los
 * componentes Swing solo se tocan desde el EDT).
 */
public class VentanaServidor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(VentanaServidor.class.getName());

    /* Nucleo de red: la ventana solo le presta su bitacora. */
    private final ServidorFideflix servidor = new ServidorFideflix(this::agregarLog);

    /**
     * Creates new form VentanaServidor
     */
    public VentanaServidor() {
        initComponents();
        lblEstado.setText("Estado: detenido");

        // AUTO-ARRANQUE: el servidor escucha apenas se crea la ventana.
        // Si el puerto ya esta ocupado, iniciarServidor() lo reporta y la
        // ventana queda en estado "detenido" con los botones habilitados.
        iniciarServidor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaLog = new javax.swing.JTextArea();
        btnIniciar = new javax.swing.JButton();
        btnDetener = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fideflix - Servidor (puerto 5000)");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Consola del servidor Fideflix");

        lblEstado.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblEstado.setText("Estado: detenido");

        areaLog.setEditable(false);
        areaLog.setColumns(20);
        areaLog.setFont(new java.awt.Font("Monospaced", 0, 13)); // NOI18N
        areaLog.setRows(5);
        jScrollPane1.setViewportView(areaLog);

        btnIniciar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnIniciar.setText("Iniciar servidor");
        btnIniciar.addActionListener(this::btnIniciarActionPerformed);

        btnDetener.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDetener.setText("Detener servidor");
        btnDetener.setEnabled(false);
        btnDetener.addActionListener(this::btnDetenerActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(lblEstado)
                .addGap(20, 20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, Short.MAX_VALUE)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnDetener, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblEstado))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDetener, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        iniciarServidor();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetenerActionPerformed
        detenerServidor();
    }//GEN-LAST:event_btnDetenerActionPerformed

    private void iniciarServidor() {
        try {
            servidor.iniciar();
            btnIniciar.setEnabled(false);
            btnDetener.setEnabled(true);
            lblEstado.setText("Estado: escuchando en el puerto " + Protocolo.PUERTO);
        } catch (IOException ex) {
            // Caso tipico: puerto ya en uso por otra instancia del servidor.
            JOptionPane.showMessageDialog(this,
                    "No se pudo iniciar el servidor: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void detenerServidor() {
        servidor.detener();
        btnIniciar.setEnabled(true);
        btnDetener.setEnabled(false);
        lblEstado.setText("Estado: detenido");
    }

    /*
     * Bitacora thread-safe: puede invocarse desde cualquier hilo (aceptador,
     * hilos de cliente); por eso salta al EDT antes de tocar el JTextArea.
     */
    private void agregarLog(String mensaje) {
        String hora = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm:ss"));
        SwingUtilities.invokeLater(() -> {
            areaLog.append("[" + hora + "] " + mensaje + "\n");
            areaLog.setCaretPosition(areaLog.getDocument().getLength());
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaServidor().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaLog;
    private javax.swing.JButton btnDetener;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEstado;
    // End of variables declaration//GEN-END:variables
}
