package fideflix.interfaz;

/*
 * LANZADOR DE CLIENTES (version para el DISENADOR de NetBeans).
 *
 * Misma funcionalidad que la version hecha a mano: cada clic en
 * [Nuevo cliente] abre una ventana de inicio de sesion independiente,
 * para demostrar N clientes simultaneos contra el mismo servidor.
 *
 * Para usarla: copiar VentanaLanzador.java Y VentanaLanzador.form JUNTOS
 * a src/fideflix/interfaz (NetBeans los empareja por nombre).
 *
 * defaultCloseOperation = DISPOSE_ON_CLOSE (valor 2 en el .form): cerrar
 * el lanzador no termina la aplicacion; el ciclo de vida lo manda la
 * VentanaServidor.
 */
public class VentanaLanzador extends javax.swing.JFrame {

    private int contadorClientes = 0;

    /**
     * Creates new form VentanaLanzador
     */
    public VentanaLanzador() {
        initComponents();
        // Arriba-izquierda para no tapar la consola del servidor (centrada).
        setLocation(40, 40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNuevoCliente = new javax.swing.JButton();
        lblContador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fideflix - Lanzador de clientes");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("El servidor ya está en ejecución. Abra los clientes que necesite:");

        btnNuevoCliente.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnNuevoCliente.setText("Nuevo cliente");
        btnNuevoCliente.addActionListener(this::btnNuevoClienteActionPerformed);

        lblContador.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblContador.setText("Clientes abiertos: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblContador)))
                .addGap(20, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContador))
                .addGap(15, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        contadorClientes++;
        lblContador.setText("Clientes abiertos: " + contadorClientes);

        ventanaInicioSesion cliente = new ventanaInicioSesion();
        // Desplazar cada cliente para que no queden apilados uno sobre otro.
        cliente.setLocation(120 + contadorClientes * 40, 120 + contadorClientes * 40);
        cliente.setVisible(true);
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblContador;
    // End of variables declaration//GEN-END:variables
}
